name: alice
description: Alice is an HTTP Inspector tool which helps debugging http requests. It catches and stores http requests and responses, which can be viewed via simple UI.
version: 0.4.1
#author: Jakub Homlala <jhomlala@gmail.com>
homepage: https://github.com/jhomlala/alice

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  flutter_local_notifications: ^19.2.1
  rxdart: ^0.28.0
  path_provider: ^2.1.5
  open_filex: ^4.7.0
  chopper: ^7.0.9
  collection: ^1.18.0
  url_launcher: ^6.3.1
  dio: ^5.4.0
  package_info_plus: ^8.3.0
  permission_handler: ^12.0.0+1
  share_plus: ^7.2.2
  sensors_plus: ^6.1.1

dev_dependencies:
  very_good_analysis: ^5.1.0

flutter:
  plugin:
    platforms:
      android:
        package: com.jhomlala.alice
        pluginClass: AlicePlugin
      ios:
        pluginClass: AlicePlugin
      macos:
        pluginClass: AlicePlugin
